import objectiveBank from "./data/objective-bank.json";
import subjectiveBank from "./data/subjective-bank.json";
import geographyBank from "./data/geography-bank.json";

export type Question = {
  id: string;
  subject: "education" | "geography";
  chapter: string;
  topic: string;
  type: "mcq" | "trueFalse" | "short" | "material";
  difficulty: "简单" | "中等" | "困难";
  stem: string;
  options?: string[];
  answer: string;
  explanation: string;
  scoringPoints?: string[];
  keywords?: string[][];
  source: string;
  sourcePage: number;
  tags: string[];
  exam?: string;
  questionNumber?: number;
  answerConfidence?: "cross-checked" | "reference-framework" | "needs-review";
};

export const educationChapters = [
  { icon: "🌱", title: "教育基础知识", subtitle: "教育本质 · 人的发展", progress: 18, color: "pink" },
  { icon: "📚", title: "中学课程", subtitle: "课程类型 · 新课改", progress: 8, color: "yellow" },
  { icon: "🧑‍🏫", title: "中学教学", subtitle: "教学规律 · 原则方法", progress: 12, color: "mint" },
  { icon: "🧠", title: "学习心理", subtitle: "记忆 · 动机 · 迁移", progress: 15, color: "purple" },
  { icon: "🌙", title: "发展心理", subtitle: "认知 · 情绪 · 人格", progress: 5, color: "blue" },
  { icon: "🫧", title: "心理辅导", subtitle: "心理健康 · 辅导方法", progress: 0, color: "pink" },
  { icon: "💗", title: "中学德育", subtitle: "德育原则 · 德育方法", progress: 10, color: "yellow" },
  { icon: "🏫", title: "班级与教师", subtitle: "班级管理 · 教师心理", progress: 0, color: "mint" },
];

export const geographyChapters = [
  { icon: "🌍", title: "地球与地图", subtitle: "经纬网 · 等高线", progress: 14, color: "blue" },
  { icon: "☀️", title: "行星地球", subtitle: "自转 · 公转 · 时间", progress: 6, color: "yellow" },
  { icon: "☁️", title: "大气与水", subtitle: "气候 · 洋流 · 水循环", progress: 4, color: "purple" },
  { icon: "⛰️", title: "地表形态", subtitle: "内外力 · 地貌判读", progress: 0, color: "mint" },
  { icon: "🏙️", title: "人文地理", subtitle: "人口 · 城市 · 产业", progress: 0, color: "pink" },
  { icon: "🗺️", title: "区域地理", subtitle: "世界 · 中国 · 可持续", progress: 0, color: "blue" },
  { icon: "🧭", title: "课程标准", subtitle: "课程理念 · 评价建议", progress: 0, color: "yellow" },
  { icon: "✏️", title: "教学设计", subtitle: "目标 · 过程 · 三板", progress: 0, color: "purple" },
];

const starterQuestions: Question[] = [
  {
    id: "edu-001",
    subject: "education",
    chapter: "教育基础知识",
    topic: "教育的本质",
    type: "mcq",
    difficulty: "简单",
    stem: "教育区别于其他社会活动的根本特征是（ ）。",
    options: ["传递社会经验", "促进社会发展", "有目的地培养人", "开展有组织的活动"],
    answer: "C",
    explanation: "教育的质的规定性，也就是教育的本质，是有目的地培养人的社会活动。“有目的”和“培养人”两个词都要抓住。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 4,
    tags: ["高频", "一级重点"],
  },
  {
    id: "edu-002",
    subject: "education",
    chapter: "教育基础知识",
    topic: "教育学人物",
    type: "mcq",
    difficulty: "简单",
    stem: "被称为“教育学之父”，其《大教学论》标志教育学成为独立学科的教育家是（ ）。",
    options: ["赫尔巴特", "夸美纽斯", "培根", "康德"],
    answer: "B",
    explanation: "夸美纽斯是“教育学之父”；赫尔巴特是“现代教育学之父”。这是最常见的人物称号易混点。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 6,
    tags: ["人物", "易混"],
  },
  {
    id: "edu-003",
    subject: "education",
    chapter: "教育基础知识",
    topic: "人的身心发展规律",
    type: "mcq",
    difficulty: "中等",
    stem: "“拔苗助长”违背了人的身心发展的（ ）。",
    options: ["顺序性", "阶段性", "差异性", "不平衡性"],
    answer: "A",
    explanation: "人的发展有一定顺序，教育要循序渐进，不能超越发展次序。阶段性强调不同年龄阶段具有不同特征。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 12,
    tags: ["规律", "情境题"],
  },
  {
    id: "edu-004",
    subject: "education",
    chapter: "中学课程",
    topic: "课程类型",
    type: "mcq",
    difficulty: "中等",
    stem: "学校墙上的科学家画像、校风和师生关系对学生产生的教育影响，属于（ ）。",
    options: ["学科课程", "活动课程", "显性课程", "隐性课程"],
    answer: "D",
    explanation: "隐性课程是学校情境中以间接、内隐方式呈现的课程，如校风、班风、校园环境和人际关系。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 17,
    tags: ["易混", "课程类型"],
  },
  {
    id: "edu-005",
    subject: "education",
    chapter: "中学教学",
    topic: "教学原则",
    type: "mcq",
    difficulty: "中等",
    stem: "教师使用模型、实物和演示实验帮助学生形成清晰表象，主要贯彻了（ ）。",
    options: ["巩固性原则", "直观性原则", "启发性原则", "量力性原则"],
    answer: "B",
    explanation: "直观性原则要求通过实物直观、模象直观和言语直观，帮助学生获得感性认识。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 23,
    tags: ["材料高频", "教学原则"],
  },
  {
    id: "edu-006",
    subject: "education",
    chapter: "学习心理",
    topic: "强化与惩罚",
    type: "mcq",
    difficulty: "困难",
    stem: "学生按时完成作业后，老师取消了他原本不喜欢的额外值日，这使他以后更愿意按时完成作业。这属于（ ）。",
    options: ["正强化", "负强化", "正惩罚", "负惩罚"],
    answer: "B",
    explanation: "行为增加，所以是强化；移除了厌恶刺激，所以是负强化。判断口诀：先看行为增减，再看刺激增减。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 31,
    tags: ["高频", "易混对决"],
  },
  {
    id: "edu-007",
    subject: "education",
    chapter: "学习心理",
    topic: "学习动机",
    type: "mcq",
    difficulty: "中等",
    stem: "根据耶克斯—多德森定律，完成困难任务时，最有利的动机强度通常是（ ）。",
    options: ["较低", "中等", "较高", "越高越好"],
    answer: "A",
    explanation: "任务越困难，最佳动机水平越低；任务容易时最佳动机水平较高。动机与效率不是简单正比关系。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 34,
    tags: ["倒U曲线", "高频"],
  },
  {
    id: "edu-008",
    subject: "education",
    chapter: "中学德育",
    topic: "德育方法",
    type: "mcq",
    difficulty: "中等",
    stem: "学校组织学生到社区参加志愿服务，在真实活动中培养责任感，主要运用了（ ）。",
    options: ["说服教育法", "榜样示范法", "实际锻炼法", "品德评价法"],
    answer: "C",
    explanation: "让学生参加实际活动，在实践中接受锻炼并形成品德，属于实际锻炼法。",
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 43,
    tags: ["德育方法", "情境题"],
  },
  {
    id: "edu-009",
    subject: "education",
    chapter: "学习心理",
    topic: "学习动机",
    type: "trueFalse",
    difficulty: "中等",
    stem: "辨析：学习动机越强，学习效率越高。",
    answer: "错误",
    explanation: "学习动机与学习效率呈倒 U 形关系，不是简单正比。动机过弱或过强都可能降低效率，最佳动机水平还会随任务难度变化。",
    scoringPoints: ["明确判断错误", "指出倒 U 形关系", "说明动机过弱或过强均不利", "说明任务越难最佳动机水平越低"],
    keywords: [["错误", "不正确"], ["倒u", "倒 u", "耶克斯", "多德森"], ["过强", "过高", "过弱", "过低"], ["任务难度", "任务越难", "困难任务"]],
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 47,
    tags: ["辨析题", "高频"],
  },
  {
    id: "edu-010",
    subject: "education",
    chapter: "中学教学",
    topic: "教学过程规律",
    type: "short",
    difficulty: "困难",
    stem: "简答：简述教学过程的四个基本规律。",
    answer: "间接经验与直接经验相统一；掌握知识与发展能力相统一；教师主导作用与学生主体作用相统一；传授知识与思想教育相统一。",
    explanation: "按点作答，每个规律写出“二者相统一”最稳。不要只写一侧。",
    scoringPoints: ["间接经验与直接经验相统一", "掌握知识与发展能力相统一", "教师主导与学生主体相统一", "传授知识与思想教育相统一"],
    keywords: [["间接经验", "直接经验"], ["知识", "能力", "智力"], ["教师主导", "学生主体"], ["传授知识", "思想教育", "品德"]],
    source: "《中学教育知识与能力》重点笔记",
    sourcePage: 21,
    tags: ["一级简答", "必背"],
  },
  {
    id: "geo-001",
    subject: "geography",
    chapter: "地球与地图",
    topic: "经纬线",
    type: "mcq",
    difficulty: "简单",
    stem: "关于经线的叙述，正确的是（ ）。",
    options: ["所有经线相互平行", "所有经线长度相等", "经线指示东西方向", "0°经线是东西半球分界线"],
    answer: "B",
    explanation: "所有经线都是连接南北两极的半圆，长度相等，指示南北方向。东西半球通常以 20°W 和 160°E 为界。",
    source: "《初中地理》三色速记手册",
    sourcePage: 2,
    tags: ["基础", "易错"],
  },
  {
    id: "geo-002",
    subject: "geography",
    chapter: "地球与地图",
    topic: "等高线",
    type: "mcq",
    difficulty: "中等",
    stem: "等高线向海拔较高处凸出时，该地形部位通常是（ ）。",
    options: ["山脊", "山谷", "鞍部", "山顶"],
    answer: "B",
    explanation: "山谷等高线向高处凸，山脊等高线向低处凸。可以记成“凸高为谷，凸低为脊”。",
    source: "《初中地理》三色速记手册",
    sourcePage: 3,
    tags: ["判图", "口诀"],
  },
  {
    id: "geo-003",
    subject: "geography",
    chapter: "行星地球",
    topic: "地球自转",
    type: "mcq",
    difficulty: "中等",
    stem: "除南北极点外，地球自转角速度约为（ ）。",
    options: ["15°/分钟", "15°/小时", "1°/小时", "4°/分钟"],
    answer: "B",
    explanation: "地球约 24 小时自转 360°，所以角速度约为 15°/小时；经度每差 1°，地方时相差 4 分钟。",
    source: "《初中地理》三色速记手册",
    sourcePage: 4,
    tags: ["公式", "基础"],
  },
  {
    id: "geo-004",
    subject: "geography",
    chapter: "行星地球",
    topic: "地方时",
    type: "mcq",
    difficulty: "困难",
    stem: "已知 120°E 的地方时为 12:00，则 90°E 的地方时为（ ）。",
    options: ["10:00", "11:00", "13:00", "14:00"],
    answer: "A",
    explanation: "两地相差 30°，地方时相差 2 小时。90°E 位于 120°E 以西，用“东加西减”，所以是 10:00。",
    source: "《初中地理》三色速记手册",
    sourcePage: 5,
    tags: ["计算", "东加西减"],
  },
  {
    id: "geo-005",
    subject: "geography",
    chapter: "大气与水",
    topic: "太阳活动",
    type: "mcq",
    difficulty: "简单",
    stem: "太阳黑子主要出现在太阳大气的（ ）。",
    options: ["日冕层", "色球层", "光球层", "电离层"],
    answer: "C",
    explanation: "黑子出现在光球层，耀斑主要出现在色球层，活动周期约为 11 年。",
    source: "《初中地理》三色速记手册",
    sourcePage: 4,
    tags: ["易混", "太阳活动"],
  },
  {
    id: "geo-006",
    subject: "geography",
    chapter: "大气与水",
    topic: "气候成因",
    type: "mcq",
    difficulty: "困难",
    stem: "南北纬 30°—40°大陆西岸形成地中海气候，主要是因为（ ）。",
    options: ["全年受赤道低压控制", "全年受西风带控制", "夏季受副热带高压、冬季受西风带控制", "夏季受信风、冬季受极地东风控制"],
    answer: "C",
    explanation: "地中海气候夏季受副热带高气压带控制，炎热干燥；冬季受西风带控制，温和多雨。",
    source: "《初中地理》三色速记手册",
    sourcePage: 8,
    tags: ["气压带风带", "综合"],
  },
  {
    id: "geo-007",
    subject: "geography",
    chapter: "课程标准",
    topic: "课程性质",
    type: "short",
    difficulty: "中等",
    stem: "简答：义务教育地理课程具有哪些基本特征？",
    answer: "区域性、综合性、思想性、生活性、实践性。",
    explanation: "五点可用“区综思生实”辅助记忆。正式答题要写完整名称。",
    scoringPoints: ["区域性", "综合性", "思想性", "生活性", "实践性"],
    keywords: [["区域"], ["综合"], ["思想"], ["生活"], ["实践"]],
    source: "《初中地理》三色速记手册",
    sourcePage: 54,
    tags: ["课标", "必背"],
  },
  {
    id: "geo-008",
    subject: "geography",
    chapter: "教学设计",
    topic: "三板技能",
    type: "mcq",
    difficulty: "简单",
    stem: "地理课堂教学中的“三板”是指（ ）。",
    options: ["板书、板图、板画", "板书、板报、板画", "板图、板画、地图", "板书、板演、板图"],
    answer: "A",
    explanation: "地理“三板”指板书、板图、板画，是地理教师重要的学科教学技能。",
    source: "《初中地理》三色速记手册",
    sourcePage: 67,
    tags: ["教学技能", "基础"],
  },
];

export const questions: Question[] = [
  ...(objectiveBank as Question[]),
  ...(subjectiveBank as Question[]),
  ...(geographyBank as Question[]),
  ...starterQuestions,
];

const starterFlashcards = [
  { front: "教育的本质是什么？", back: "教育是一种有目的地培养人的社会活动。", tag: "科目二 · 一级重点" },
  { front: "教育学之父 vs 现代教育学之父", back: "夸美纽斯：教育学之父；赫尔巴特：现代教育学之父。", tag: "科目二 · 易混" },
  { front: "短时记忆进入长时记忆的关键", back: "复述。短时记忆的信息经过复述才能进入长时记忆。", tag: "科目二 · 高频" },
  { front: "负强化和惩罚怎么区分？", back: "负强化是移除厌恶刺激以增加行为；惩罚是为了减少行为。", tag: "科目二 · 易混" },
  { front: "等高线判山谷、山脊口诀", back: "凸高为谷，凸低为脊；等高线密陡、疏缓。", tag: "地理 · 判图" },
  { front: "地方时计算口诀", back: "东加西减，同减异加；经度每差 1°，地方时相差 4 分钟。", tag: "地理 · 公式" },
  { front: "太阳黑子和耀斑分别在哪层？", back: "黑子在光球层，耀斑在色球层，太阳活动周期约 11 年。", tag: "地理 · 易混" },
  { front: "义务教育地理课程五个特征", back: "区域性、综合性、思想性、生活性、实践性。", tag: "地理 · 课标" },
];

const truthAndFrameworkCards = questions
  .filter((question) => question.subject === "education" && question.type !== "material")
  .map((question) => {
    const optionIndex = "ABCD".indexOf(question.answer);
    const choice = optionIndex >= 0 ? question.options?.[optionIndex] : "";
    return {
      front: question.stem,
      back: question.type === "mcq" ? `${question.answer}. ${choice || ""}` : question.answer,
      tag: `${question.exam || "科目二"} · ${question.type === "mcq" ? "真题速记" : "主观题框架"}`,
    };
  });

export const flashcards = [...starterFlashcards, ...truthAndFrameworkCards];
